### ISSUE TITLE
Reactjs Haчaлo - Задания/Решения

### ISSUE THREAD

**Issue by telxehbuhtig** [githubhexlet/jsbackendprogrammer#1]
Будут ли добавлены задания и решения для курса Reаctjs Haчaлo?

**Comment by githubhexlet** [comment]
то что уже опубликовано, это информация из открытых источников, с гитхаба
по курсу Reactjs находятся только решения,  https://github.com/GlaIZier/js_react_beginning_hexlet_course

**Comment by telxehbuhtig** [comment]
Спасибо вам за информацию!
